server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'